### ISSUE TITLE
Increase time precision?

### ISSUE THREAD

**Issue by bplatz** [maxcountryman/flake#8]
Great library, and I know this is a port, but I'd like to see support for 100-nanosecond precision (where available). I noticed you are utilizing nanoTime now.

I don't know the rationale of having the MAC/machine ID in the middle, but this would seem to provide ordering with more precision: [millis-timestamp:64][100nano+sequence:16][MAC:48]

You could provide up to 100 nano precision with the same bits (consistent with UUID-1)... and where the precision lacks the sequence is used to fill in any remaining bits.

Any thoughts?

**Comment by maxcountryman** [comment]
Thanks for the comments!

I'm curious what use-case 100-nanosecond precision provides that isn't already provided by millisecond resolution plus a sequence? Given that the sequence is incremented whenever we generate an ID in the same millisecond, we effectively end up with most of the same benefits of a more granular timestamp.

To address your question about ordering, one of the problems with UUID-1 (mentioned in the Boundary [README](https://github.com/boundary/flake/blob/a21d7f23867410c1ad5ee7fe1e9e296bfb5b0c02/readme.md#frequently-asked-questions), actually) is that moving the least significant bits around breaks lexicographic ordering.

**Comment by bplatz** [comment]
I'm looking for additional ordering precision with distributed nodes. The other side-benefit is a lower probability of collision if two workers happen to have the same MAC. The latter could also be accomplished using a rolling counter started at a random number (don't reset every millisecond).

My particular case allows for external entities (outside of my direct environment) to generate IDs that need guaranteed time ordering. The current scheme would group writes in the same millisecond by machine.

**Comment by maxcountryman** [comment]
Another approach I've seen some implementations take is to use a process identifier. This is what [Skuld does](https://github.com/Factual/skuld/blob/202d6870fdbe461f4387d0cac8b8680a0fc9aae2/src/skuld/flake.clj#L36-L40), for instance. However, a side effect of this is IDs are necessarily larger, in terms of bytes.

I guess I'm not opposed to higher fidelity timestamps so long as it doesn't increase the size of IDs. That said, it does kind of seem like it's papering over the underlying issue you described, where two workers might share a MAC and thus there's a chance of duplicate IDs.

Also I should point out that if you know two workers share a MAC, you can provide a custom worker ID to `generate!`--for example, you could use a process identifier and some bits from the MAC in place of the MAC.

**Comment by bplatz** [comment]
One idea for fidelity while maintaining total bit size: the first 64 bits could have more precision. Nanosecond precision would still allow values out to the year 2554 (unsigned, so that value would only fit in a Long through year 2262)

(-> (Math/pow 2 64)
      (quot 1000000)
      (java.time.Instant/ofEpochMilli))
;;=> "2554-07-21T23:34:33.709Z"

Microsecond precision gets things out to the year 294247.
100 Nanoseconds (same as UUID-1) would be year 60425
10 Nanoseconds is year 7815

For me, the year 2554 is plenty good, so I think I'll go that route.

If less granular precision, having the 16-bit sequence before the MAC bits would allow it to be used for addition precision and preserve ordering.

Of course all this would result in breaking changes for your library.

**Comment by maxcountryman** [comment]
Currently we are constructing an epoch from the difference between `currentTimeMillis` and `nanoTime` and then effectively counting from there by adding `nanoTime` to the epoch and dividing that by one million. I don't think we stand to gain anything in terms of longevity for ID generation by tweaking precision here unless I'm misunderstanding something.

I certainly want the library to be flexible and meet the needs of its users. However I don't think it would be a good idea to make radical changes to the anatomy of the IDs at this point. I've tried to expose the various bits of data used to construct IDs so that consumers can make application-level decisions about those things, e.g. the worker IDs.

Another possibility would be the inclusion of a new generator for similar but distinct IDs. I'm not sure the additional library API complexity is necessarily worth it though.

**Comment by bplatz** [comment]
Sounds good and sounds like the right decision for the library. My solution will be to generate nano-second precision in the first 64-bits and place the mac address last. This could allow the sequence to instead hold pico-seconds if/when that is available and still maintain ordering.

I'm going to use base-58 encoding and may prepend the final string with a "0" to allow me to change ID formats in the future but still maintain ordering.

If any of those changes you desired incorporated, let me know. I'll close the issue, and thanks for your timely responses.

**Comment by maxcountryman** [comment]
I really appreciate your comments here--I'm certainly open to changes while maintaining backwards compatibility as best we can. It might even be worth including a different generator at some point as well.
