### ISSUE TITLE
base 62 alphabet order

### ISSUE THREAD

**Issue by bplatz** [maxcountryman/flake#9]
The alphabet order is incorrect for proper sorting.

Current:
"0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"

Should be:
"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"

**Comment by maxcountryman** [comment]
Thanks for reporting this!
